
jenkins-global:
  environment: load-env
  globalActionEnabled: true
  globalAction: update
  baseurl: https://jenkins.dp.net
  J_USERNAME: username
  J_PASS: test
  successMsg: 'Finished: SUCCESS'
  maxTimeForTab: 240
  maxTimeForWholeRun: 15 # IN MINUTES
  sleepBeforeEachCycleStart: 20
  sleepBeforeEachTabOpens: 10

deployment:
  service-name:
    url: /job/manage/ENVIRONMENT/build?delay=0sec
    deploy: true
    action: status
    version: 1.0.0